# Exported from Render on 2025-02-04T08:46:58Z
services:
- type: web
  name: my_api
  runtime: docker
  repo: https://github.com/Langtok/my_api
  branch: dev
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: SECRET_KEY_BASE
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
