---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/leagues":
    get:
      summary: Retrieve all leagues
      tags:
      - Leagues
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        country:
                          type: string
                        season:
                          type: string
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
